// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOA1vuEWqqh7p2Jb9kd_pbbf-5c4eIusU',
    appId: '1:266438057657:web:83a7a554858a7032334568',
    messagingSenderId: '266438057657',
    projectId: 'roktobondhon-919',
    authDomain: 'roktobondhon-919.firebaseapp.com',
    storageBucket: 'roktobondhon-919.firebasestorage.app',
    measurementId: 'G-RDZCTEDEZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzX2OYjVG0evInTVSa0TJwQTPYMb3pPWE',
    appId: '1:266438057657:android:053394c937388d7f334568',
    messagingSenderId: '266438057657',
    projectId: 'roktobondhon-919',
    storageBucket: 'roktobondhon-919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8L3T6vUxqupby8iVu_jpJ16EupScJSY',
    appId: '1:266438057657:ios:6da139369613df2f334568',
    messagingSenderId: '266438057657',
    projectId: 'roktobondhon-919',
    storageBucket: 'roktobondhon-919.firebasestorage.app',
    iosBundleId: 'com.example.roktoBondhon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8L3T6vUxqupby8iVu_jpJ16EupScJSY',
    appId: '1:266438057657:ios:6da139369613df2f334568',
    messagingSenderId: '266438057657',
    projectId: 'roktobondhon-919',
    storageBucket: 'roktobondhon-919.firebasestorage.app',
    iosBundleId: 'com.example.roktoBondhon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOA1vuEWqqh7p2Jb9kd_pbbf-5c4eIusU',
    appId: '1:266438057657:web:b5269e8763992092334568',
    messagingSenderId: '266438057657',
    projectId: 'roktobondhon-919',
    authDomain: 'roktobondhon-919.firebaseapp.com',
    storageBucket: 'roktobondhon-919.firebasestorage.app',
    measurementId: 'G-DWXRNXYGMR',
  );
}
